// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sacrament_final.Data;

namespace Sacrament_final.Migrations
{
    [DbContext(typeof(Sacrament_finalContext))]
    [Migration("20200405051500_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sacrament_final.Models.Sacrament", b =>
                {
                    b.Property<int>("SacramentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClosingPrayer")
                        .IsRequired();

                    b.Property<string>("ConductingLeader")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("IntermediateHymn")
                        .IsRequired();

                    b.Property<string>("OpenignSong")
                        .IsRequired();

                    b.Property<string>("OpeningPrayer")
                        .IsRequired();

                    b.Property<string>("Speaker")
                        .IsRequired();

                    b.Property<string>("SpeakerThree");

                    b.Property<string>("SpeakerTopic")
                        .IsRequired();

                    b.Property<string>("SpeakerTwo");

                    b.HasKey("SacramentId");

                    b.ToTable("Sacrament");
                });
#pragma warning restore 612, 618
        }
    }
}
